#!/bin/sh
# audio_menu.sh - generate the waybar audio output-device menu.
#
# Parses `wpctl status` for audio sinks and writes two runtime files:
#   ~/.cache/waybar/audio_menu.xml   GtkMenu for waybar's "menu" option
#   ~/.cache/waybar/audio_sinks.map  menu slot -> PipeWire node id
#
# Waybar reads the menu XML only at startup, so this script runs before
# waybar starts (sway config: `exec_always sh -c 'pkill -x waybar;
# audio_menu.sh; exec waybar'`). Reload sway to pick up newly connected
# devices.
#
# Menu item ids must match the "menu-actions" keys in config.jsonc, which are
# static (sink1..sink8), so slots are assigned in wpctl order and resolved to
# node ids through the map file.

set -eu

cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/waybar"
mkdir -p "$cache_dir"
xml="$cache_dir/audio_menu.xml"
map="$cache_dir/audio_sinks.map"
tmp_xml="$xml.$$"
tmp_map="$map.$$"
max_slots=8

: > "$tmp_map"

wpctl status 2>/dev/null | sed -n '/Sinks:/,/Sources:/p' | awk -v max_slots="$max_slots" -v map="$tmp_map" '
function esc(s) {
    gsub(/&/, "\\&amp;", s)
    gsub(/</, "\\&lt;", s)
    gsub(/>/, "\\&gt;", s)
    gsub(/_/, "__", s) # "_" would become a GTK mnemonic (use_underline)
    return s
}
BEGIN {
    print "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
    print "<!-- Generated by audio_menu.sh; do not edit. -->"
    print "<interface>"
    print "  <object class=\"GtkMenu\" id=\"menu\">"
    n = 0
}
{
    if (match($0, /[0-9][0-9]*\./)) {
        id = substr($0, RSTART, RLENGTH - 1)
        label = substr($0, RSTART + RLENGTH)
        sub(/^[[:space:]]+/, "", label)
        sub(/[[:space:]]*\[[^]]*\][[:space:]]*$/, "", label)
        # the sink id is the first "<digits>." in the line (no apostrophes
        # here: the awk program sits inside single quotes)
        if (++n <= max_slots) {
            print "    <child>"
            print "      <object class=\"GtkMenuItem\" id=\"sink" n "\">"
            print "        <property name=\"label\">" esc(label) "</property>"
            print "      </object>"
            print "    </child>"
            print "sink" n " " id > map
        }
    }
}
END {
    print "  </object>"
    print "</interface>"
}
' > "$tmp_xml"

mv "$tmp_xml" "$xml"
mv "$tmp_map" "$map"
